default:
  image: gradle:6.8.1-jdk11
  before_script:
    - apt-get update && apt-get install -y make && apt-get install -y ruby && apt-get install -y ruby-dev
    - gem update && gem install rest-client

stages:
  - build
  - frontend-test
  - backend-test

build job:
  stage: build
  script:
    - make
  only:
    - master

invalid syntax test job:
  stage: frontend-test
  script:
    - make test TESTCLASS="frontend.InvalidSyntaxTests"
  only:
    - master

invalid semantics test job:
  stage: frontend-test
  script:
    - make test TESTCLASS="frontend.InvalidSemanticTests"
  only:
    - master

valid frontend test job:
  stage: frontend-test
  script:
    - make test TESTCLASS="frontend.TypeSemanticsTests"
    - make test TESTCLASS="frontend.ValidTests"
  only:
    - master

valid backend test job:
  stage: backend-test
  script:
    - make test TESTCLASS="backend.ValidTests"
  only:
    - master