default:
  image: gradle:6.8.1-jdk11
  before_script:
    - apt-get update && apt-get install -y make

build job:
  stage: build
  script:
    - make
  only:
    - master

invalid syntax test job:
  stage: test
  script:
    - make test TESTCLASS="frontend.InvalidSyntaxTests"
  only:
    - master

invalid semantics test job:
  stage: test
  script:
    - make test TESTCLASS="frontend.InvalidSemanticTests"
  only:
    - master

valid test job:
  stage: test
  script:
    - make test TESTCLASS="frontend.TypeSemanticsTests"
    - make test TESTCLASS="frontend.ValidTests"
  only:
    - master